import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import Sidebar from './components/Sidebar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en">
      <body>
        <div className="drawer lg:drawer-open">
          <input
            id="my-drawer-4"
            type="checkbox"
            className="drawer-toggle inline"
          />
          <div className="drawer-content">
            <Navbar />
            <div className="p-4">{children}</div>
          </div>
          <Sidebar />
        </div>
      </body>
    </html>
  );
}
